plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

include:
  - _includes

just_the_docs:
  search_enabled: true
  include_head: true
  custom_css:
    - "assets/css/custom.scss"

remote_theme: hydecorp/hydejack

author: Akshit
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge