title: ML Learning
description: A brief collection of personally assembled notes and resources for data science and machine learning
repository: akshitv2/MLLearning
remote_theme: just-the-docs/just-the-docs

permalink: pretty
search_enabled: false
include_head: false
heading_anchors: true
author: Akshit