title: My Project Docs
description: Documentation for my awesome project
baseurl: "" # Leave empty for project site at https://username.github.io/repo-name/
url: "http://akshitv2.github.io/MLLearning/" # Change to your GitHub Pages URL

theme: minima   # GitHub-supported theme (simple, clean)

markdown: kramdown
kramdown:
  input: GFM   # GitHub Flavored Markdown

# Include these files in the site
include:
  - index.md

# Exclude things from being published
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
