plugins:
  - jekyll-include-cache
  - jekyll-remote-theme

remote_theme: just-the-docs/just-the-docs

author: Akshit
markdown: kramdown
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge  # Optional: Keeps code highlighting working